### ISSUE TITLE
TextGrids?

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#268]
Maybe this is because I don't know how the directory needs to be set up -- but I created a mini-sub-folder of the CSJ called "CSJ_subset" that has three TextGrid files in it and nothing else, and tried to use that as a spontaneous speech corpus with TextGrid as the file set-up option, and got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/qt/corpusgui.py", line 71, in run
    call_back = self.kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/spontaneous.py", line 192, in import_spontaneous_speech_corpus
    data = textgrids_to_data(v['textgrid'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/spontaneous.py", line 32, in textgrids_to_data
    tg.read(path)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 719, in read
    itie.addPoint(Point(jtim, jmrk))
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 313, in addPoint
    raise ValueError(point)# we already got one right there
ValueError: Point(1063.61532, EUAP)

**Comment by kchall** [comment]
This was the error when I used the whole folder:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/qt/corpusgui.py", line 71, in run
    call_back = self.kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/spontaneous.py", line 173, in import_spontaneous_speech_corpus
    dialogs = align_textgrid_info(textgrids, wavs, stop_check, call_back)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/spontaneous.py", line 141, in align_textgrid_info
    dialogs[name]['wav'] = p3
KeyError: 'a01f0067'

**Comment by mmcauliffe** [comment]
Ok, so I've resolved the first issue (though praat shouldn't have generated that textgrid with two points at the same time, so something's a bit wonky there), in a bit of a hackish manner, mostly because it doesn't currently care about point tiers (I don't know what use they'd be over interval tiers, anyway).

The second error is caused because the name of the wav file doesn't match the name of the textgrid (one's lower case, the other's upper case), which again, shouldn't have been produced by Praat.  I can do some hackish things to fix that, but I'd rather wait for access to the legit corpus to see what their naming scheme is actually like.

One thing to note for using textgrids is that the lexical entries don't have transcriptions, they only have transcriptions associated with their word tokens, so you'd get access to them via the "List production variants" or through transforming the text view into a table and there will be a column for the individual token's transcriptions.
