### ISSUE TITLE
PCT is broken. :(

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#294]
Just synced the latest version and tried to run it...

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/bin/pct_qt_debug.py", line 6, in <module>
    from corpustools.gui.qt.main import MainWindow,QApplicationMessaging
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/main.py", line 7, in <module>
    from .config import Settings, PreferencesDialog
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/config.py", line 8, in <module>
    from .widgets import DirectoryWidget
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/widgets.py", line 6, in <module>
    from .views import TableWidget
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/views.py", line 164
    if attribute
               ^
SyntaxError: invalid syntax

**Comment by mmcauliffe** [comment]
Sorry, yes, should be fixed now.
