### ISSUE TITLE
Removing selected rows in environment lists

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#335]
When multiple rows are selected in lists of environments, and "Delete selected environments" is chosen, not all environments actually delete. Some do, others don't. The following error occurs:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1390, in removeEnv
    self.table.model().removeRow(s.row())
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/models.py", line 65, in removeRow
    del self.rows[ind]
IndexError: list assignment index out of range

**Comment by mmcauliffe** [comment]
Should be fixed now!
