### ISSUE TITLE
Phonological search bug?

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#340]
Hmm, this was working on an older version, but seems to be busted in the latest one....

Anyway: I was doing a phonological search for a pair of vowels in a set of different consonantal environments in the LF_syllables.txt corpus, and got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 542, in phonoSearch
    'Phonological search results',dialog,self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/views.py", line 812, in __init__
    dataModel.setSummarized(True)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 472, in setSummarized
    self._summarize()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 459, in _summarize
    tokenfreq[segenv] += line[0].frequency
TypeError: unsupported operand type(s) for +=: 'float' and 'str'

**Comment by mmcauliffe** [comment]
This isn't the version posted to dropbox, right?  This is the one with N/A in it?  In which case, this will get fixed when the N/A support in #320 is implemented.

**Comment by kchall** [comment]
Ah, right...yep. Different corpora on different laptops. Sorry. Thanks.
