### ISSUE TITLE
create corpus from csv error

### ISSUE THREAD

**Issue by bhallen** [kchall/CorpusTools#341]
Attempted to use the GUI to create a corpus from LF_syllables_v2.txt (should be available in Dropbox), with column delimiter and transcription delimiter left blank. Result is an exception and frozen window:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/corpustools-1.0.0-py3.4.egg/corpustools/corpus/classes/lexicon.py", line 1748, in add_word
    check = self.find(word.spelling, keyerror=True)
  File "/usr/local/lib/python3.4/dist-packages/corpustools-1.0.0-py3.4.egg/corpustools/corpus/classes/lexicon.py", line 1896, in find
    raise KeyError('The word \"{}\" is not in the corpus'.format(word))
KeyError: 'The word "bah" is not in the corpus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/corpustools-1.0.0-py3.4.egg/corpustools/gui/corpusgui.py", line 1493, in accept
    corpus = load_corpus_csv(name, path, colDelim, transDelim, featureSystem)
  File "/usr/local/lib/python3.4/dist-packages/corpustools-1.0.0-py3.4.egg/corpustools/corpus/io/csv.py", line 84, in load_corpus_csv
    corpus.add_word(word)
  File "/usr/local/lib/python3.4/dist-packages/corpustools-1.0.0-py3.4.egg/corpustools/corpus/classes/lexicon.py", line 1769, in add_word
    self.orthography.update(word.spelling)
AttributeError: 'Corpus' object has no attribute 'orthography'

**Comment by bhallen** [comment]
Actually the column delimiter is a tab, the default.

**Comment by mmcauliffe** [comment]
Try the latest master, I should have already fixed this.

**Comment by bhallen** [comment]
I'm up to date with origin/master, and the problem is still here. It happens when I try to create a corpus from the command line too.

**Comment by mmcauliffe** [comment]
Whoops, I committed it but didn't push it!  Sorry about that!

**Comment by bhallen** [comment]
Works great now, thanks!
