### ISSUE TITLE
Load corpus error

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#343]
Hmm, I seem to be getting the following error in trying to load in any version of the Gitksan corpus I have:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 174, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 241, in loadCorpus
    self.textWidget.setModel(DiscourseModel(self.corpus, self.settings))
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/views.py", line 598, in setModel
    if AUDIO_ENABLED and model.hasAudio():
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 290, in hasAudio
    return self.corpus.has_audio()
TypeError: 'bool' object is not callable

My other corpora are loading ok, though.

**Comment by mmcauliffe** [comment]
Should be fixed as of the latest commit.
