### ISSUE TITLE
Edit word details not working

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#349]
Using a newly created Gitksan corpus and updated feature file, I added a column to indicate which language each word comes from, because some words are English. Trying to edit individual words, I get the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 206, in editWord
    dialog = AddWordDialog(self, self.corpusModel.corpus, word)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 908, in __init__
    self.edits[a.name] = TranscriptionWidget('Transcription',self.corpus.inventory)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 929, in __init__
    self.segments = InventoryBox('Inventory',self.inventory)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 652, in __init__
    c = s.category
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 199, in category
    elif self.features['labiodental'] == '+':
KeyError: 'labiodental'

**Comment by kchall** [comment]
The same error also prevents me from being able to add pairs of sounds or environments in any analyses.

**Comment by kchall** [comment]
(There is no labiodental feature in the feature file.)

**Comment by kchall** [comment]
Once I added labiodental, trill, and tap as features, it works...so I guess this is really the same issue as #348.
